FROM debian:bullseye

RUN apt-get update \
    && apt-get install -y --no-install-recommends nginx \
    && rm -rf /var/lib/apt/lists/*

COPY conf/nginx.conf /etc/nginx/nginx.conf
COPY website/ /var/www/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"] 